param (
    [Parameter(Mandatory = $false)]
    [switch]$AutoInstallOverride,
    [Parameter(Mandatory = $false)]
    [ValidateSet('Scheduled', 'OnDemand')]
    [string]$RunReason = 'Scheduled'
)

$basePath = Join-Path $env:APPDATA 'winget-app-setup'
$configPath = Join-Path $basePath 'update-config.json'
$checksPath = Join-Path $basePath 'update-checks'
$rollbackPath = Join-Path $basePath 'rollback-scripts'
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$dateStamp = Get-Date -Format 'yyyyMMdd'
$detailedLogFile = Join-Path $checksPath "update-check-$dateStamp.log"
$fallbackNotificationLog = Join-Path $env:APPDATA "winget-updates-$dateStamp.log"

foreach ($path in @($basePath, $checksPath, $rollbackPath)) {
    if (-not (Test-Path $path)) {
        New-Item -Path $path -ItemType Directory -Force | Out-Null
    }
}

function Write-UpdateLog {
    param (
        [Parameter(Mandatory = $true)]
        [string]$Message
    )
    "$((Get-Date).ToString('yyyy-MM-dd HH:mm:ss')) - $Message" | Add-Content -Path $detailedLogFile
}

function Get-DefaultConfig {
    return @{
        EnabledScheduledUpdates = $false
        UpdateFrequency         = 'Weekly'
        AutoInstall             = $true
        LastCheckDate           = $null
        Enabled                 = $false
        InitialPromptCompleted  = $false
    }
}

function Get-Config {
    if (-not (Test-Path $configPath)) {
        return (Get-DefaultConfig)
    }

    try {
        $config = Get-Content -Path $configPath -Raw | ConvertFrom-Json
        return @{
            EnabledScheduledUpdates = [bool]$config.EnabledScheduledUpdates
            UpdateFrequency         = if ($config.UpdateFrequency -in @('Weekly', 'Daily')) { [string]$config.UpdateFrequency } else { 'Weekly' }
            AutoInstall             = [bool]$config.AutoInstall
            LastCheckDate           = $config.LastCheckDate
            Enabled                 = [bool]$config.Enabled
            InitialPromptCompleted  = [bool]$config.InitialPromptCompleted
        }
    }
    catch {
        Write-UpdateLog "Failed to parse configuration. Using defaults. Error: $_"
        return (Get-DefaultConfig)
    }
}

function Save-Config {
    param (
        [Parameter(Mandatory = $true)]
        [hashtable]$Config
    )
    $Config | ConvertTo-Json | Set-Content -Path $configPath -Encoding UTF8
}

function Get-UpdateReport {
    try {
        if (Get-Command Get-WinGetPackage -ErrorAction SilentlyContinue) {
            return @(Get-WinGetPackage | Where-Object IsUpdateAvailable | ForEach-Object {
                    [PSCustomObject]@{
                        PackageName      = $_.Id
                        CurrentVersion   = [string]$_.InstalledVersion
                        AvailableVersion = [string]$_.AvailableVersion
                    }
                })
        }
    }
    catch {
        Write-UpdateLog "Module update query failed. Falling back to CLI. Error: $_"
    }

    $report = @()
    $upgradeOutput = & winget upgrade --disable-interactivity --accept-source-agreements 2>&1
    foreach ($line in $upgradeOutput) {
        if (-not $line) { continue }
        if ($line -match '^\s*Name\s+Id\s+Version\s+Available') { continue }
        if ($line -match '^\s*-{3,}') { continue }
        if ($line -match 'No installed package found|No available upgrade found|No newer package versions are available') { continue }
        $columns = $line.Trim() -split '\s{2,}'
        if ($columns.Count -ge 4 -and $columns[1] -match '^[\w][\w.\-]+\.[\w][\w.\-]+$') {
            $report += [PSCustomObject]@{
                PackageName      = $columns[1]
                CurrentVersion   = $columns[2]
                AvailableVersion = $columns[3]
            }
        }
    }

    return @($report | Sort-Object PackageName -Unique)
}

function Write-RollbackScript {
    param (
        [Parameter(Mandatory = $true)]
        [array]$UpdatedPackages
    )

    if ($UpdatedPackages.Count -eq 0) {
        return
    }

    $rollbackScript = Join-Path $rollbackPath ("rollback-{0}.ps1" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))
    $scriptLines = @(
        '# Rollback script generated by winget-app-setup',
        '# Restores previous versions for packages updated in the last run',
        ''
    )
    foreach ($pkg in $UpdatedPackages) {
        if (-not [string]::IsNullOrWhiteSpace($pkg.CurrentVersion)) {
            $scriptLines += "winget install --id `"$($pkg.PackageName)`" --version `"$($pkg.CurrentVersion)`" -e --accept-source-agreements --accept-package-agreements --disable-interactivity"
        }
    }
    $scriptLines | Set-Content -Path $rollbackScript -Encoding UTF8
    Write-UpdateLog "Rollback script generated: $rollbackScript"
}

function Send-UpdateToast {
    param (
        [Parameter(Mandatory = $true)]
        [string]$SummaryText,
        [Parameter(Mandatory = $true)]
        [string[]]$Details
    )

    try {
        Add-Type -AssemblyName System.Runtime.WindowsRuntime -ErrorAction Stop
        [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
        [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom.XmlDocument, ContentType = WindowsRuntime] | Out-Null

        $normalizedDetails = @($Details | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        if ($normalizedDetails.Count -eq 0) {
            $normalizedDetails = @('No package details available.')
        }
        $escapedDetails = ($normalizedDetails | ForEach-Object { [System.Security.SecurityElement]::Escape($_) })
        $body = ($escapedDetails -join '</text><text>')
        $xml = @"
<toast>
  <visual>
    <binding template="ToastGeneric">
      <text>Winget Updates Available</text>
      <text>$([System.Security.SecurityElement]::Escape($SummaryText))</text>
      <text>$body</text>
      <text>$([System.Security.SecurityElement]::Escape("Timestamp: $timestamp"))</text>
    </binding>
  </visual>
</toast>
"@

        $xmlDoc = New-Object Windows.Data.Xml.Dom.XmlDocument
        $xmlDoc.LoadXml($xml)
        $toast = [Windows.UI.Notifications.ToastNotification]::new($xmlDoc)
        $notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('winget-app-setup')
        $notifier.Show($toast)
        return $true
    }
    catch {
        return $false
    }
}

$config = Get-Config
$autoInstall = if ($PSBoundParameters.ContainsKey('AutoInstallOverride')) { [bool]$AutoInstallOverride } else { [bool]$config.AutoInstall }
$updates = @(Get-UpdateReport)

if ($updates.Count -eq 0) {
    Write-UpdateLog "[$RunReason] No updates available."
    $config.LastCheckDate = (Get-Date).ToString('yyyy-MM-dd')
    Save-Config -Config $config
    exit 0
}

$successfulUpdates = @()
$failedUpdates = @()

if ($autoInstall) {
    foreach ($update in $updates) {
        try {
            $upgradeOutput = & winget upgrade -e --id $update.PackageName --accept-source-agreements --accept-package-agreements --disable-interactivity 2>&1
            $wingetExitCode = $LASTEXITCODE
            if ($wingetExitCode -eq 0) {
                $successfulUpdates += $update
                Write-UpdateLog "SUCCESS | $($update.PackageName) | $($update.CurrentVersion) -> $($update.AvailableVersion)"
            }
            else {
                $failedUpdates += $update
                Write-UpdateLog "FAILED  | $($update.PackageName) | $($update.CurrentVersion) -> $($update.AvailableVersion) | ExitCode: $wingetExitCode | Output: $($upgradeOutput | Out-String)"
            }
        }
        catch {
            $failedUpdates += $update
            Write-UpdateLog "FAILED  | $($update.PackageName) | $($update.CurrentVersion) -> $($update.AvailableVersion) | Error: $_"
        }
    }
}
else {
    foreach ($update in $updates) {
        Write-UpdateLog "AVAILABLE | $($update.PackageName) | $($update.CurrentVersion) -> $($update.AvailableVersion)"
    }
}

if ($successfulUpdates.Count -gt 0) {
    Write-RollbackScript -UpdatedPackages $successfulUpdates
}

$config.LastCheckDate = (Get-Date).ToString('yyyy-MM-dd')
Save-Config -Config $config

$updatedCount = if ($autoInstall) { $successfulUpdates.Count } else { 0 }
$summary = if ($autoInstall) { "$updatedCount packages updated successfully" } else { "$($updates.Count) updates available" }
$detailLines = @()
if ($autoInstall) {
    $detailLines += $successfulUpdates | ForEach-Object { "$($_.PackageName): $($_.CurrentVersion) → $($_.AvailableVersion)" }
}
else {
    $detailLines += $updates | ForEach-Object { "$($_.PackageName): $($_.CurrentVersion) → $($_.AvailableVersion)" }
}

if (-not (Send-UpdateToast -SummaryText $summary -Details $detailLines)) {
    @(
        "Winget Updates Available"
        $summary
        $detailLines
        "Timestamp: $timestamp"
    ) | Set-Content -Path $fallbackNotificationLog -Encoding UTF8
    Write-UpdateLog "Toast notification failed. Fallback log written to: $fallbackNotificationLog"
}
