# WindowsTerminal.Tests.ps1
# Tests for WingetAppSetup/Public/WindowsTerminal.ps1 and Private/Jsonc.ps1: default
# profile configuration (the targeted settings.json edit), JSONC sanitizing and editing,
# registry defaults, and orchestration (including the SYSTEM and cross-user skips).
# Split from the old single-file suite Test-WingetAppInstall.Tests.ps1 (issue #192).

# Load the module's functions once for this file. TestHelpers.ps1 resolves the repo paths
# and dot-sources WingetAppSetup/Private + Public (the single source of truth; the
# distributable winget-app-install.ps1 is generated from it by build/Build-WingetInstallScript.ps1).
BeforeAll {
    . (Join-Path $PSScriptRoot 'TestHelpers.ps1')
}

Describe 'Windows Terminal configuration' {
    BeforeAll {
    }

    Context 'Set-WindowsTerminalDefaultProfile' {
        It 'Should set defaultProfile in settings.json' {
            $settingsPath = Join-Path $TestDrive 'settings.json'
            Set-Content -Path $settingsPath -Value '{"profiles":{"list":[]}}' -Encoding UTF8

            $result = Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
            $updated = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json

            $result | Should -Be $true
            $updated.defaultProfile | Should -Be '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
        }

        It 'Should parse JSONC style settings with comments and trailing commas' {
            $settingsPath = Join-Path $TestDrive 'settings-jsonc.json'
            $jsonc = @'
{
  // sample comment
  "profiles": {
    "list": [
    ],
  },
}
'@
            Set-Content -Path $settingsPath -Value $jsonc -Encoding UTF8

            $result = Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid '574e775e-4f2a-5b96-ac1e-a2962a402336'
            $updated = Get-Content -Path $settingsPath -Raw | ConvertFrom-Json

            $result | Should -Be $true
            $updated.defaultProfile | Should -Be '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
        }

        It 'Should return false when settings path does not exist' {
            $missingPath = Join-Path $TestDrive 'missing-settings.json'

            $result = Set-WindowsTerminalDefaultProfile -SettingsPath $missingPath -ProfileGuid '{574e775e-4f2a-5b96-ac1e-a2962a402336}'

            $result | Should -Be $false
        }
    }

    Context 'Set-WindowsTerminalDefaultProfile keeps the rest of a hand-edited settings.json' {
        BeforeAll {
            $pwsh7Guid = '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
            # A settings.json as people keep it: Windows Terminal's header comments, an admin's note,
            # a commented-out profile parked for later (with a "defaultProfile" key of its own),
            # trailing commas, inline objects, an inline comment and a // inside a string.
            $handEditedSettings = @'
// This file was initially generated by Windows Terminal 1.21.2361.0
// It should still be usable in newer versions, but newer versions might have additional
// settings, help text, or changes that you will not see unless you clear this file
// and let us generate a new one for you.

// To view the default settings, hover over "defaultProfile" or read the docs.
{
    "$help": "https://aka.ms/terminal-documentation",
    "$schema": "https://aka.ms/terminal-profiles-schema",
    "actions": [ { "command": { "action": "copy", "singleLine": false }, "keys": "ctrl+c" }, ],
    "copyFormatting": "none",
    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", // Windows PowerShell for now
    // Company-mandated font -- do not change (ticket IT-1234)
    "profiles":
    {
        "defaults": { "font": { "face": "Cascadia Mono" } },
        "list":
        [
            /* Parked until the new jump host is up:
            {
                "name": "Old SSH profile",
                "commandline": "ssh admin@old-jump",
                "defaultProfile": "not-a-real-key"
            },
            */
            {
                "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
                "name": "Windows PowerShell",
                "commandline": "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
                "hidden": false,
            },
            {
                "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
                "name": "PowerShell",
                "source": "Windows.Terminal.PowershellCore", // docs: "https://aka.ms//terminal"
            },
        ]
    },
    "schemes": [],
}

'@
            $oldDefaultLine = '    "defaultProfile": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}", // Windows PowerShell for now'
            $newDefaultLine = '    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}", // Windows PowerShell for now'
            # The same file before anyone set a default profile, with a commented-out default line.
            $settingsWithoutDefault = $handEditedSettings.Replace(
                $oldDefaultLine, '    // "defaultProfile": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",')
            $insertedDefaultLine = '    "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",'

            function Write-SettingsFixture {
                param ([string]$Name, [byte[]]$Bytes)
                $path = Join-Path $TestDrive $Name
                [System.IO.File]::WriteAllBytes($path, $Bytes)
                return $path
            }
            function Get-Utf8Bytes {
                param ([string]$Text)
                return , [System.Text.UTF8Encoding]::new($false).GetBytes($Text)
            }
        }

        It 'Replaces only the defaultProfile value: comments, the parked profile and formatting stay byte-for-byte' {
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $settingsPath = Write-SettingsFixture 'replace-settings.json' $originalBytes
            $expected = $handEditedSettings.Replace($oldDefaultLine, $newDefaultLine)
            $expected | Should -Not -BeExactly $handEditedSettings

            $result = Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid

            $result | Should -BeTrue
            [System.IO.File]::ReadAllText($settingsPath) | Should -BeExactly $expected
        }

        It 'Inserts a missing defaultProfile before the first key and changes nothing else' {
            $settingsPath = Write-SettingsFixture 'insert-settings.json' (Get-Utf8Bytes $settingsWithoutDefault)
            $expected = $settingsWithoutDefault.Replace(
                "`n    `"`$help`"", "`n$insertedDefaultLine`n    `"`$help`"")
            $expected | Should -Not -BeExactly $settingsWithoutDefault

            $result = Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid

            $result | Should -BeTrue
            [System.IO.File]::ReadAllText($settingsPath) | Should -BeExactly $expected
        }

        It 'Saves the original file as settings.json.winget-app-setup.bak and leaves no temporary file' {
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $folder = Join-Path $TestDrive 'backup'
            New-Item -ItemType Directory -Path $folder | Out-Null
            $settingsPath = Join-Path $folder 'settings.json'
            [System.IO.File]::WriteAllBytes($settingsPath, $originalBytes)

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeTrue

            $backupPath = Join-Path $folder 'settings.json.winget-app-setup.bak'
            Test-Path -LiteralPath $backupPath | Should -BeTrue
            [System.IO.File]::ReadAllBytes($backupPath) | Should -Be $originalBytes
            @(Get-ChildItem -LiteralPath $folder -Name | Sort-Object) | Should -Be @('settings.json', 'settings.json.winget-app-setup.bak')

            # A later change replaces the backup with the file as it was just before that change.
            $firstEditBytes = [System.IO.File]::ReadAllBytes($settingsPath)
            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid '{0caa0dad-35be-5f56-a8ff-afceeeaa6101}' | Should -BeTrue
            [System.IO.File]::ReadAllBytes($backupPath) | Should -Be $firstEditBytes
        }

        It 'Writes through a symbolic link: the link stays and the linked file gets the change' {
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $dotfilesFolder = Join-Path $TestDrive 'dotfiles'
            $linkFolder = Join-Path $TestDrive 'symlink'
            New-Item -ItemType Directory -Path $dotfilesFolder, $linkFolder | Out-Null
            $targetPath = Join-Path $dotfilesFolder 'settings.json'
            [System.IO.File]::WriteAllBytes($targetPath, $originalBytes)
            $settingsPath = Join-Path $linkFolder 'settings.json'
            try {
                New-Item -ItemType SymbolicLink -Path $settingsPath -Target $targetPath -ErrorAction Stop | Out-Null
            }
            catch {
                # Windows allows it only to an administrator or with Developer Mode on.
                Set-ItResult -Skipped -Because "this account cannot create symbolic links: $_"
                return
            }

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeTrue

            (Get-Item -LiteralPath $settingsPath -Force).LinkType | Should -Be 'SymbolicLink'
            [System.IO.File]::ReadAllText($targetPath) | Should -BeExactly $handEditedSettings.Replace($oldDefaultLine, $newDefaultLine)
            $backupPath = "$settingsPath.winget-app-setup.bak"
            [System.IO.File]::ReadAllBytes($backupPath) | Should -Be $originalBytes
            (Get-Item -LiteralPath $backupPath -Force).LinkType | Should -BeNullOrEmpty
            @(Get-ChildItem -LiteralPath $linkFolder -Name | Sort-Object) | Should -Be @('settings.json', 'settings.json.winget-app-setup.bak')
        }

        It 'Writes through a hard link: both names still share one file, which has the change' {
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $folder = Join-Path $TestDrive 'hardlink'
            New-Item -ItemType Directory -Path $folder | Out-Null
            $otherNamePath = Join-Path $folder 'dotfiles-settings.json'
            [System.IO.File]::WriteAllBytes($otherNamePath, $originalBytes)
            $settingsPath = Join-Path $folder 'settings.json'
            New-Item -ItemType HardLink -Path $settingsPath -Target $otherNamePath -ErrorAction Stop | Out-Null

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeTrue

            (Get-Item -LiteralPath $settingsPath -Force).LinkType | Should -Be 'HardLink'
            [System.IO.File]::ReadAllText($otherNamePath) | Should -BeExactly $handEditedSettings.Replace($oldDefaultLine, $newDefaultLine)
            [System.IO.File]::ReadAllBytes("$settingsPath.winget-app-setup.bak") | Should -Be $originalBytes
            Test-Path -LiteralPath "$settingsPath.winget-app-setup.tmp" | Should -BeFalse
        }

        It 'Keeps CRLF line endings and a UTF-8 byte-order mark' {
            $crlfText = $settingsWithoutDefault.Replace("`n", "`r`n")
            $bom = [byte[]](0xEF, 0xBB, 0xBF)
            $settingsPath = Write-SettingsFixture 'crlf-bom-settings.json' ([byte[]]($bom + (Get-Utf8Bytes $crlfText)))
            $expected = $crlfText.Replace(
                "`r`n    `"`$help`"", "`r`n$insertedDefaultLine`r`n    `"`$help`"")

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeTrue

            $bytes = [System.IO.File]::ReadAllBytes($settingsPath)
            $bytes[0..2] | Should -Be $bom
            [System.Text.UTF8Encoding]::new($false).GetString($bytes, 3, $bytes.Length - 3) | Should -BeExactly $expected
        }

        It 'Leaves the file unchanged and returns false when the edited text would change another setting' {
            Mock Write-WarningMessage { }
            # Simulates an editing bug: the result parses and has the new defaultProfile, but lost a setting.
            Mock Set-JsoncTopLevelStringProperty { '{ "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}" }' }
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $settingsPath = Write-SettingsFixture 'invalid-edit-settings.json' $originalBytes

            $result = Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid

            $result | Should -BeFalse
            [System.IO.File]::ReadAllBytes($settingsPath) | Should -Be $originalBytes
            Test-Path -LiteralPath "$settingsPath.winget-app-setup.bak" | Should -BeFalse
            Should -Invoke Write-WarningMessage -Times 1 -ParameterFilter { $Message -match 'left unchanged' }
        }

        It 'Leaves the file unchanged when defaultProfile holds an object it cannot replace' {
            Mock Write-WarningMessage { }
            $originalBytes = Get-Utf8Bytes "{`n    `"defaultProfile`": { `"guid`": `"x`" }, // odd`n    `"a`": 1`n}`n"
            $settingsPath = Write-SettingsFixture 'object-value-settings.json' $originalBytes

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeFalse

            [System.IO.File]::ReadAllBytes($settingsPath) | Should -Be $originalBytes
        }

        It 'Leaves the file unchanged when the backup cannot be written' {
            Mock Write-WarningMessage { }
            Mock Copy-Item { throw 'Access to the path is denied.' }
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $settingsPath = Write-SettingsFixture 'no-backup-settings.json' $originalBytes

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeFalse

            [System.IO.File]::ReadAllBytes($settingsPath) | Should -Be $originalBytes
            Should -Invoke Write-WarningMessage -Times 1 -ParameterFilter { $Message -match 'Failed to update' }
        }

        It 'Leaves the file unchanged when the new content cannot be written' {
            Mock Write-WarningMessage { }
            $originalBytes = Get-Utf8Bytes $handEditedSettings
            $settingsPath = Write-SettingsFixture 'blocked-temp-settings.json' $originalBytes
            # A directory where the temporary file would go makes the write fail.
            New-Item -ItemType Directory -Path "$settingsPath.winget-app-setup.tmp" | Out-Null

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeFalse

            [System.IO.File]::ReadAllBytes($settingsPath) | Should -Be $originalBytes
            Should -Invoke Write-WarningMessage -Times 1 -ParameterFilter { $Message -match 'Failed to update' }
        }

        It 'Leaves a file that is not valid UTF-8 unchanged' {
            Mock Write-WarningMessage { }
            # "caf" + 0xE9 (Windows-1252 e-acute): decoding it would turn it into U+FFFD on write-back.
            $originalBytes = [byte[]](Get-Utf8Bytes '{ "a": "caf') + [byte[]](0xE9) + [byte[]](Get-Utf8Bytes '" }')
            $settingsPath = Write-SettingsFixture 'latin1-settings.json' ([byte[]]$originalBytes)

            Set-WindowsTerminalDefaultProfile -SettingsPath $settingsPath -ProfileGuid $pwsh7Guid | Should -BeFalse

            [System.IO.File]::ReadAllBytes($settingsPath) | Should -Be $originalBytes
            Should -Invoke Write-WarningMessage -Times 1 -ParameterFilter { $Message -match 'UTF-8' }
        }
    }

    Context 'Set-JsoncTopLevelStringProperty' {
        It 'Replaces only the top-level value, not a nested, commented-out or quoted key of the same name' {
            $jsonc = @'
{
    // "defaultProfile": "commented",
    /* "defaultProfile": "block", */
    "note": "\"defaultProfile\": \"in a string\"",
    "profiles": { "list": [ { "defaultProfile": "nested" } ] },
    "defaultProfile": "old", // keep me
}
'@
            $expected = $jsonc.Replace('"defaultProfile": "old"', '"defaultProfile": "new"')

            Set-JsoncTopLevelStringProperty -JsonText $jsonc -Name 'defaultProfile' -Value 'new' | Should -BeExactly $expected
        }

        It 'Replaces a non-string value and every duplicate of the key' {
            Set-JsoncTopLevelStringProperty -JsonText '{ "defaultProfile": null, "a": 1, "defaultProfile": "x" }' -Name 'defaultProfile' -Value 'new' |
                Should -BeExactly '{ "defaultProfile": "new", "a": 1, "defaultProfile": "new" }'
        }

        It 'Matches the key case-sensitively, as Windows Terminal does' {
            Set-JsoncTopLevelStringProperty -JsonText '{ "DefaultProfile": "x" }' -Name 'defaultProfile' -Value 'new' |
                Should -BeExactly '{ "defaultProfile": "new", "DefaultProfile": "x" }'
        }

        It "Inserts the key on its own line with the first key's indentation and the file's line endings" {
            $jsonc = "// header`r`n{`r`n`t// first`r`n`t`"a`": 1`r`n}`r`n"

            Set-JsoncTopLevelStringProperty -JsonText $jsonc -Name 'defaultProfile' -Value 'new' |
                Should -BeExactly "// header`r`n{`r`n`t// first`r`n`t`"defaultProfile`": `"new`",`r`n`t`"a`": 1`r`n}`r`n"
        }

        It 'Inserts the key inline when the first key shares its line with the opening brace' {
            Set-JsoncTopLevelStringProperty -JsonText '{"a":{"b":1}}' -Name 'defaultProfile' -Value 'new' |
                Should -BeExactly '{"defaultProfile": "new", "a":{"b":1}}'
        }

        It 'Fills an empty root object, and creates one for empty text' {
            Set-JsoncTopLevelStringProperty -JsonText '{}' -Name 'defaultProfile' -Value 'new' |
                Should -BeExactly '{ "defaultProfile": "new" }'
            Set-JsoncTopLevelStringProperty -JsonText '' -Name 'defaultProfile' -Value 'new' |
                Should -BeExactly "{`n    `"defaultProfile`": `"new`"`n}`n"
        }

        It 'Escapes quotes and backslashes in the value' {
            $result = Set-JsoncTopLevelStringProperty -JsonText '{ "a": 1 }' -Name 'name' -Value 'C:\x "y"'

            $result | Should -BeExactly '{ "name": "C:\\x \"y\"", "a": 1 }'
            ($result | ConvertFrom-Json).name | Should -BeExactly 'C:\x "y"'
        }

        It 'Returns $null when the root is not an object or the current value is an object or an array' {
            Set-JsoncTopLevelStringProperty -JsonText '[ { "defaultProfile": "x" } ]' -Name 'defaultProfile' -Value 'new' | Should -BeNullOrEmpty
            Set-JsoncTopLevelStringProperty -JsonText '{ "defaultProfile": { "x": 1 } }' -Name 'defaultProfile' -Value 'new' | Should -BeNullOrEmpty
            Set-JsoncTopLevelStringProperty -JsonText '{ "defaultProfile": [ "x" ] }' -Name 'defaultProfile' -Value 'new' | Should -BeNullOrEmpty
        }
    }

    Context 'Convert-JsoncToJson sanitizer' {
        It 'Should strip a trailing inline comment after a value' {
            $jsonc = @'
{
  "copyOnSelect": true, // keep this setting
  "defaultProfile": "{574e775e-4f2a-5b96-ac1e-a2962a402336}"
}
'@
            $sanitized = Convert-JsoncToJson -JsonText $jsonc

            $sanitized | Should -Not -Match 'keep this setting'
            $parsed = $sanitized | ConvertFrom-Json
            $parsed.copyOnSelect | Should -BeTrue
            $parsed.defaultProfile | Should -Be '{574e775e-4f2a-5b96-ac1e-a2962a402336}'
        }

        It 'Should preserve comment-like sequences inside string values' {
            $jsonc = @'
{
  "commandline": "cmd /* not a comment */ //still-not",
  "url": "https://example.com/path"
}
'@
            $parsed = Convert-JsoncToJson -JsonText $jsonc | ConvertFrom-Json

            $parsed.commandline | Should -Be 'cmd /* not a comment */ //still-not'
            $parsed.url | Should -Be 'https://example.com/path'
        }

        It 'Should honor escaped quotes so \" does not end the string' {
            $jsonc = @'
{
  "name": "quoted \" // not a comment",
  "next": 1 // real comment
}
'@
            $sanitized = Convert-JsoncToJson -JsonText $jsonc

            $sanitized | Should -Not -Match 'real comment'
            $parsed = $sanitized | ConvertFrom-Json
            $parsed.name | Should -Be 'quoted " // not a comment'
            $parsed.next | Should -Be 1
        }

        It 'Should strip full-line comments' {
            $jsonc = @'
{
  // full-line comment
  "a": 1
}
'@
            $sanitized = Convert-JsoncToJson -JsonText $jsonc

            $sanitized | Should -Not -Match 'full-line comment'
            ($sanitized | ConvertFrom-Json).a | Should -Be 1
        }

        It 'Should strip block comments spanning multiple lines' {
            $jsonc = @'
{
  /* block comment
     spanning lines */
  "a": 1,
  "b": /* inline block */ 2
}
'@
            $sanitized = Convert-JsoncToJson -JsonText $jsonc

            $sanitized | Should -Not -Match 'block comment'
            $parsed = $sanitized | ConvertFrom-Json
            $parsed.a | Should -Be 1
            $parsed.b | Should -Be 2
        }

        It 'Should remove trailing commas, including one separated from the closer by a comment' {
            $jsonc = @'
{
  "list": [1, 2, /* trailing */ ],
  "a": 1,
}
'@
            $parsed = Convert-JsoncToJson -JsonText $jsonc | ConvertFrom-Json

            $parsed.list.Count | Should -Be 2
            $parsed.a | Should -Be 1
        }

        It 'Should not treat comma-plus-closer content inside strings as a trailing comma' {
            $jsonc = @'
{
  "text": "a, ]"
}
'@
            (Convert-JsoncToJson -JsonText $jsonc | ConvertFrom-Json).text | Should -Be 'a, ]'
        }

        It 'Should parse settings with a trailing inline comment end-to-end' {
            $jsonc = @'
{
  "copyOnSelect": true, // keep
  "profiles": { "list": [] }
}
'@
            $parsed = ConvertFrom-TerminalSettingsJson -JsonText $jsonc

            $parsed | Should -Not -BeNullOrEmpty
            $parsed.copyOnSelect | Should -BeTrue
        }
    }

    Context 'Set-WindowsTerminalAsDefaultTerminalApplication' {
        It 'Should create/update registry values when not already configured' {
            Mock Test-Path { return $false } -ParameterFilter { $Path -eq 'HKCU:\Console\%%Startup' }
            Mock New-Item { }
            Mock Get-ItemProperty { return [pscustomobject]@{} }
            Mock New-ItemProperty { }

            $result = Set-WindowsTerminalAsDefaultTerminalApplication

            $result | Should -Be $true
            Should -Invoke New-Item -Times 1 -ParameterFilter { $Path -eq 'HKCU:\Console\%%Startup' -and $Force }
            Should -Invoke New-ItemProperty -Times 2
        }

        It 'Should skip writes when registry is already configured' {
            Mock Test-Path { return $true } -ParameterFilter { $Path -eq 'HKCU:\Console\%%Startup' }
            Mock Get-ItemProperty {
                [pscustomobject]@{
                    DelegationConsole  = '{2EACA947-7F5F-4CFA-BA87-8F7FBEEFBE69}'
                    DelegationTerminal = '{E12CFF52-A866-4C77-9A90-F570A7AA2C6B}'
                }
            }
            Mock New-ItemProperty { }

            $result = Set-WindowsTerminalAsDefaultTerminalApplication

            $result | Should -Be $true
            Should -Invoke New-ItemProperty -Times 0
        }

        It 'Should return false when registry write fails' {
            Mock Test-Path { return $true } -ParameterFilter { $Path -eq 'HKCU:\Console\%%Startup' }
            Mock Get-ItemProperty { return [pscustomobject]@{} }
            Mock New-ItemProperty { throw 'Registry denied' }

            $result = Set-WindowsTerminalAsDefaultTerminalApplication

            $result | Should -Be $false
        }
    }

    Context 'Set-WindowsTerminalDefaults orchestration' {
        BeforeEach {
            # Deterministic same-user, non-SYSTEM state by default; the skip tests override.
            Mock Test-IsSystemAccount { $false }
            Mock Get-ProcessUserName { 'CONTOSO\jdoe' }
            Mock Get-InteractiveSessionUserName { 'CONTOSO\jdoe' }
            Mock Write-WarningMessage { }
            # Windows Terminal is present by default (issue #271); the "not installed" gate is
            # covered by its own tests below.
            Mock Test-WindowsTerminalInstalled { $true }
        }

        It 'Should perform no writes in WhatIf mode' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }

            Set-WindowsTerminalDefaults -WhatIf

            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 0
            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 0
            Should -Invoke Write-Info -Times 2
        }

        It 'Should configure both settings file and registry in normal mode' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }

            Set-WindowsTerminalDefaults

            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 1
            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 1
        }

        It 'Should configure all discovered settings files in normal mode' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\stable-settings.json', 'C:\temp\preview-settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }

            Set-WindowsTerminalDefaults

            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 2
            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 1
        }

        It 'Should configure the logged-on user without a skip line when process and session users match' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }

            Set-WindowsTerminalDefaults

            Should -Invoke Write-Info -Times 0 -ParameterFilter { $Message -match 'Skipping Windows Terminal defaults' }
            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 1
        }

        It 'Skips the whole step with one line under cross-user elevation, writing nothing for the admin account' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }
            Mock Get-ProcessUserName { 'CONTOSO\admin-tech' }
            Mock Get-InteractiveSessionUserName { 'CONTOSO\jdoe' }

            Set-WindowsTerminalDefaults

            Should -Invoke Write-Info -Times 1 -Exactly
            Should -Invoke Write-Info -Times 1 -Exactly -ParameterFilter {
                $Message -match '^Skipping Windows Terminal defaults: they are per-user' -and
                $Message -match "'CONTOSO\\admin-tech'" -and $Message -match "'CONTOSO\\jdoe'"
            }
            Should -Invoke Write-WarningMessage -Times 0
            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 0
            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 0
        }

        It 'Skips under cross-user elevation in WhatIf mode too, without previewing writes' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }
            Mock Get-ProcessUserName { 'CONTOSO\admin-tech' }
            Mock Get-InteractiveSessionUserName { 'CONTOSO\jdoe' }

            Set-WindowsTerminalDefaults -WhatIf

            Should -Invoke Write-Info -Times 1 -Exactly
            Should -Invoke Write-Info -Times 0 -ParameterFilter { $Message -match 'DRY-RUN' }
            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 0
        }

        It 'Skips the whole step with one SYSTEM line when running as SYSTEM, even with a user logged on' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }
            Mock Test-IsSystemAccount { $true }
            Mock Get-ProcessUserName { 'NT AUTHORITY\SYSTEM' }
            Mock Get-InteractiveSessionUserName { 'CONTOSO\jdoe' }

            Set-WindowsTerminalDefaults

            Should -Invoke Write-Info -Times 1 -Exactly
            Should -Invoke Write-Info -Times 1 -Exactly -ParameterFilter { $Message -match 'this run is SYSTEM' }
            Should -Invoke Write-WarningMessage -Times 0
            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 0
            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 0
        }

        It 'Still configures the process account when the interactive user is unknown' {
            Mock Get-WindowsTerminalSettingsPaths { return @('C:\temp\settings.json') }
            Mock Set-WindowsTerminalDefaultProfile { return $true }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }
            Mock Get-ProcessUserName { 'CONTOSO\admin-tech' }
            Mock Get-InteractiveSessionUserName { $null }

            Set-WindowsTerminalDefaults

            Should -Invoke Write-Info -Times 0 -ParameterFilter { $Message -match 'Skipping Windows Terminal defaults' }
            Should -Invoke Set-WindowsTerminalDefaultProfile -Times 1
            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 1
        }

        It 'Skips the default-terminal-application registry write when Windows Terminal is not installed (issue #271)' {
            Mock Get-WindowsTerminalSettingsPaths { return @() }
            Mock Test-WindowsTerminalInstalled { $false }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }

            Set-WindowsTerminalDefaults

            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 0
            Should -Invoke Write-WarningMessage -ParameterFilter { $Message -match 'Windows Terminal is not installed' }
        }

        It 'Previews skipping the default-terminal-application write in WhatIf mode when Windows Terminal is not installed' {
            Mock Get-WindowsTerminalSettingsPaths { return @() }
            Mock Test-WindowsTerminalInstalled { $false }
            Mock Set-WindowsTerminalAsDefaultTerminalApplication { return $true }
            Mock Write-Info { }

            Set-WindowsTerminalDefaults -WhatIf

            Should -Invoke Set-WindowsTerminalAsDefaultTerminalApplication -Times 0
            Should -Invoke Write-Info -ParameterFilter { $Message -match 'not installed' -and $Message -match 'skip' }
        }
    }
}
